# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotations',
            options={'verbose_name': 'Annotation', 'verbose_name_plural': 'Annotations'},
        ),
        migrations.AlterField(
            model_name='annotations',
            name='height',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='shape_type',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='src',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='width',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='y',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
